### ISSUE TITLE
An guide please?

### ISSUE THREAD

**Issue by TheMrMarcks** [RPP1011/WizardsOfLegend#1]
Hi, which are the steps to try this mod?? What changes it makes to the base game??

**Comment by RPP1011** [comment]
Hi, sorry this mod is not quite ready to play yet. The intended change to the base game is to make the local co-op game mode work over the remotely.

**Comment by TheMrMarcks** [comment]
> Hi, sorry this mod is not quite ready to play yet. The intended change to the base game is to make the local co-op game mode work over the remotely.

Nice, i really like this game and always wanted online multiplayer on it, im going to follow this proyect, thanks in advance for this :)
